package dev.yekta.book4us.api

import org.intellij.lang.annotations.Language

@Suppress("SqlNoDataSourceInspection", "SqlDialectInspection")
@Language("SQL")
internal const val INITIAL_TEMP_DATA = """
    INSERT INTO Book (author, cover_image, description, publication_year, title, genres) VALUES
        ('Harper Lee', 'https://picsum.photos/seed/0/667/1000', 'A classic novel depicting racial injustice in the American South.', '1960', 'To Kill a Mockingbird', 'Fiction,Classic'),
        ('George Orwell', 'https://picsum.photos/seed/1/667/1000', 'A dystopian novel portraying a totalitarian society.', '1949', '1984', 'Dystopian,Science Fiction'),
        ('Jane Austen', 'https://picsum.photos/seed/2/667/1000', 'A classic novel exploring themes of love, marriage, and social norms.', '1813', 'Pride and Prejudice', 'Classic,Romance'),
        ('F. Scott Fitzgerald', 'https://picsum.photos/seed/3/667/1000', 'A tale of the American Dream, wealth, and love during the Roaring Twenties.', '1925', 'The Great Gatsby', 'Fiction,Classic'),
        ('Herman Melville', 'https://picsum.photos/seed/4/667/1000', 'The epic tale of Captain Ahab''s obsession with the white whale.', '1851', 'Moby-Dick', 'Fiction,Adventure'),
        ('J.R.R. Tolkien', 'https://picsum.photos/seed/5/667/1000', 'An epic fantasy saga about the quest to destroy the One Ring.', '1954', 'The Lord of the Rings', 'Fantasy,Adventure'),
        ('J.D. Salinger', 'https://picsum.photos/seed/6/667/1000', 'A classic coming-of-age novel following Holden Caulfield''s journey.', '1951', 'The Catcher in the Rye', 'Fiction,Coming-of-age'),
        ('J.R.R. Tolkien', 'https://picsum.photos/seed/7/667/1000', 'The prequel to The Lord of the Rings, following Bilbo Baggins'' journey.', '1937', 'The Hobbit', 'Fantasy,Adventure'),
        ('Gabriel Garcia Marquez', 'https://picsum.photos/seed/8/667/1000', 'A multi-generational saga of the Buendía family in the fictional town of Macondo.', '1967', 'One Hundred Years of Solitude', 'Magical Realism,Literary Fiction'),
        ('Leo Tolstoy', 'https://picsum.photos/seed/9/667/1000', 'A monumental work depicting the events of Russian society during the Napoleonic era.', '1869', 'War and Peace', 'Historical Fiction,Epic'),
        ('Homer', 'https://picsum.photos/seed/10/667/1000', 'An ancient Greek epic poem recounting Odysseus'' ten-year journey home after the Trojan War.', '8th century BCE', 'The Odyssey', 'Epic,Mythology'),
        ('Dante Alighieri', 'https://picsum.photos/seed/11/667/1000', 'An epic poem that follows the journey of the soul through Hell, Purgatory, and Heaven.', '1320', 'The Divine Comedy', 'Epic,Poetry'),
        ('Fyodor Dostoevsky', 'https://picsum.photos/seed/12/667/1000', 'A complex novel exploring themes of spirituality, morality, and human nature.', '1880', 'The Brothers Karamazov', 'Classic,Philosophical Fiction'),
        ('Fyodor Dostoevsky', 'https://picsum.photos/seed/13/667/1000', 'A psychological thriller revolving around guilt, conscience, and redemption.', '1866', 'Crime and Punishment', 'Classic,Psychological Fiction'),
        ('Oscar Wilde', 'https://picsum.photos/seed/14/667/1000', 'A novel about a man whose portrait ages while he retains his youth and beauty.', '1890', 'The Picture of Dorian Gray', 'Gothic,Philosophical Fiction'),
        ('Aldous Huxley', 'https://picsum.photos/seed/15/667/1000', 'A dystopian vision of a future society obsessed with pleasure and conformity.', '1932', 'Brave New World', 'Dystopian,Science Fiction'),
        ('Alexandre Dumas', 'https://picsum.photos/seed/16/667/1000', 'An adventure novel of revenge, love, and redemption set in the early 19th century.', '1844', 'The Count of Monte Cristo', 'Adventure,Historical Fiction'),
        ('Leo Tolstoy', 'https://picsum.photos/seed/17/667/1000', 'A tragic love story set against the backdrop of Russian high society.', '1877', 'Anna Karenina', 'Classic,Romance'),
        ('Paulo Coelho', 'https://picsum.photos/seed/18/667/1000', 'A philosophical novel about a shepherd boy''s journey to find his personal legend.', '1988', 'The Alchemist', 'Fiction,Philosophical'),
        ('Mark Twain', 'https://picsum.photos/seed/19/667/1000', 'A satirical novel following Huck Finn''s journey down the Mississippi River.', '1884', 'The Adventures of Huckleberry Finn', 'Adventure,Satire'),
        ('Homer', 'https://picsum.photos/seed/20/667/1000', 'An ancient Greek epic poem about the Trojan War and the hero Achilles.', '8th century BCE', 'The Iliad', 'Epic,Mythology'),
        ('J.R.R. Tolkien', 'https://picsum.photos/seed/21/667/1000', 'A thrilling epic about the quest to destroy the One Ring and save Middle-earth from the dark lord Sauron.', '1954', 'The Lord of the Rings', 'Fantasy,Adventure'),
        ('Miguel de Cervantes', 'https://picsum.photos/seed/22/667/1000', 'A satirical novel about a deluded knight and his faithful squire, Sancho Panza.', '1605', 'Don Quixote', 'Classic,Satire'),
        ('Mary Shelley', 'https://picsum.photos/seed/23/667/1000', 'A novel about the creation of a monster and the consequences of playing god.', '1818', 'Frankenstein', 'Gothic,Science Fiction'),
        ('Lewis Carroll', 'https://picsum.photos/seed/24/667/1000', 'A whimsical tale about a girl named Alice who falls into a magical world.', '1865', 'Alice''s Adventures in Wonderland', 'Fantasy,Children''s Literature'),
        ('Antoine de Saint-Exupéry', 'https://picsum.photos/seed/25/667/1000', 'A philosophical novella about a young prince''s journey through the universe.', '1943', 'The Little Prince', 'Fable,Children''s Literature'),
        ('Markus Zusak', 'https://picsum.photos/seed/26/667/1000', 'A story of a girl living in Nazi Germany, narrated by Death.', '2005', 'The Book Thief', 'Historical Fiction,War'),
        ('Kurt Vonnegut', 'https://picsum.photos/seed/27/667/1000', 'An anti-war novel that mixes science fiction and dark humor.', '1969', 'Slaughterhouse-Five', 'Satire,Science Fiction'),
        ('John Steinbeck', 'https://picsum.photos/seed/28/667/1000', 'A novel about the plight of migrant workers during the Great Depression.', '1939', 'The Grapes of Wrath', 'Historical Fiction,Social Commentary'),
        ('Ray Bradbury', 'https://picsum.photos/seed/29/667/1000', 'A dystopian novel depicting a future society where books are banned.', '1953', 'Fahrenheit 451', 'Dystopian,Science Fiction'),
        ('William Golding', 'https://picsum.photos/seed/30/667/1000', 'A novel about a group of British boys stranded on an uninhabited island.', '1954', 'The Lord of the Flies', 'Dystopian,Psychological Fiction'),
        ('Douglas Adams', 'https://picsum.photos/seed/31/667/1000', 'A comedic science fiction series about the misadventures of Arthur Dent.', '1979', 'The Hitchhiker''s Guide to the Galaxy', 'Science Fiction,Comedy'),
        ('Charles Dickens', 'https://picsum.photos/seed/32/667/1000', 'A historical novel set during the French Revolution, exploring themes of sacrifice and resurrection.', '1859', 'A Tale of Two Cities', 'Historical Fiction,Classic'),
        ('C.S. Lewis', 'https://picsum.photos/seed/33/667/1000', 'A series of fantasy novels set in the magical land of Narnia.', '1950', 'The Chronicles of Narnia', 'Fantasy,Children''s Literature'),
        ('Margaret Atwood', 'https://picsum.photos/seed/34/667/1000', 'A dystopian novel set in a totalitarian society where women are subjugated.', '1985', 'The Handmaid''s Tale', 'Dystopian,Feminist Fiction'),
        ('Umberto Eco', 'https://picsum.photos/seed/35/667/1000', 'A medieval mystery novel set in an Italian monastery.', '1980', 'The Name of the Rose', 'Historical Fiction,Mystery'),
        ('Franz Kafka', 'https://picsum.photos/seed/36/667/1000', 'A surreal novel exploring themes of guilt, law, and justice.', '1925', 'The Trial', 'Absurdist Fiction,Existential'),
        ('Khaled Hosseini', 'https://picsum.photos/seed/37/667/1000', 'A novel about friendship, redemption, and the impact of war in Afghanistan.', '2003', 'The Kite Runner', 'Historical Fiction,Drama'),
        ('Ken Follett', 'https://picsum.photos/seed/38/667/1000', 'An epic historical novel set in 12th-century England, centered around the construction of a cathedral.', '1989', 'The Pillars of the Earth', 'Historical Fiction,Adventure'),
        ('Carlos Ruiz Zafón', 'https://picsum.photos/seed/39/667/1000', 'A mystery novel set in post-war Barcelona, revolving around a forgotten book and its author.', '2001', 'The Shadow of the Wind', 'Mystery,Gothic'),
        ('Frances Hodgson Burnett', 'https://picsum.photos/seed/40/667/1000', 'A classic children''s novel about a young girl who discovers a hidden garden.', '1911', 'The Secret Garden', 'Children''s Literature,Classic'),
        ('Lois Lowry', 'https://picsum.photos/seed/41/667/1000', 'A dystopian novel about a society with strict control over emotions and memories.', '1993', 'The Giver', 'Dystopian,Young Adult'),
        ('Franz Kafka', 'https://picsum.photos/seed/42/667/1000', 'A novella about a man who wakes up one morning transformed into a giant insect.', '1915', 'The Metamorphosis', 'Absurdist Fiction,Existential'),
        ('Margaret Mitchell', 'https://picsum.photos/seed/43/667/1000', 'A historical novel set during the American Civil War, centered around Scarlett O''Hara.', '1936', 'Gone with the Wind', 'Historical Fiction,Romance'),
        ('Kenneth Grahame', 'https://picsum.photos/seed/44/667/1000', 'A children''s novel about the adventures of anthropomorphic animals.', '1908', 'The Wind in the Willows', 'Children''s Literature,Fantasy'),
        ('Bram Stoker', 'https://picsum.photos/seed/45/667/1000', 'A Gothic horror novel about the vampire Count Dracula''s attempt to move to England.', '1897', 'Dracula', 'Gothic,Horror'),
        ('Jack London', 'https://picsum.photos/seed/46/667/1000', 'An adventure novel about a domestic dog''s life in the wilds of the Yukon.', '1903', 'The Call of the Wild', 'Adventure,Nature'),
        ('Stephen King', 'https://picsum.photos/seed/47/667/1000', 'A post-apocalyptic horror novel about a deadly pandemic and its aftermath.', '1978', 'The Stand', 'Horror,Post-Apocalyptic'),
        ('Alice Walker', 'https://picsum.photos/seed/48/667/1000', 'A novel about the life of African-American women in the Southern United States.', '1982', 'The Color Purple', 'Fiction,Historical'),
        ('J.R.R. Tolkien', 'https://picsum.photos/seed/49/667/1000', 'A collection of mythopoeic stories about the history of Middle-earth.', '1977', 'The Silmarillion', 'Fantasy,Mythopoe');
    """
